# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exifViewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExifViewer(object):
    def setupUi(self, ExifViewer):
        ExifViewer.setObjectName("ExifViewer")
        ExifViewer.resize(1812, 1007)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ExifViewer.sizePolicy().hasHeightForWidth())
        ExifViewer.setSizePolicy(sizePolicy)
        ExifViewer.setMinimumSize(QtCore.QSize(0, 0))
        ExifViewer.setMaximumSize(QtCore.QSize(1920, 1080))
        ExifViewer.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(ExifViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ViewerImage_Layout = QtWidgets.QVBoxLayout()
        self.ViewerImage_Layout.setObjectName("ViewerImage_Layout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Geolocalization = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Geolocalization.sizePolicy().hasHeightForWidth())
        self.Geolocalization.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Geolocalization.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/pin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Geolocalization.setIcon(icon)
        self.Geolocalization.setIconSize(QtCore.QSize(40, 40))
        self.Geolocalization.setFlat(False)
        self.Geolocalization.setObjectName("Geolocalization")
        self.verticalLayout.addWidget(self.Geolocalization, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.RotateLeft_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RotateLeft_2.sizePolicy().hasHeightForWidth())
        self.RotateLeft_2.setSizePolicy(sizePolicy)
        self.RotateLeft_2.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/LeftRotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RotateLeft_2.setIcon(icon1)
        self.RotateLeft_2.setIconSize(QtCore.QSize(40, 40))
        self.RotateLeft_2.setFlat(True)
        self.RotateLeft_2.setObjectName("RotateLeft")
        self.horizontalLayout.addWidget(self.RotateLeft_2)
        self.RotateRight_2 = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RotateRight_2.sizePolicy().hasHeightForWidth())
        self.RotateRight_2.setSizePolicy(sizePolicy)
        self.RotateRight_2.setMinimumSize(QtCore.QSize(33, 27))
        self.RotateRight_2.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/RightRotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.RotateRight_2.setIcon(icon2)
        self.RotateRight_2.setIconSize(QtCore.QSize(40, 40))
        self.RotateRight_2.setFlat(True)
        self.RotateRight_2.setObjectName("RotateRight")
        self.horizontalLayout.addWidget(self.RotateRight_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ViewerImage_Layout.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(2000, 2000))
        self.label.setAcceptDrops(True)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Pictures/Screenshot from 2020-07-19 22-26-23.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.ViewerImage_Layout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.BeforeAfterLayout = QtWidgets.QHBoxLayout()
        self.BeforeAfterLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.BeforeAfterLayout.setObjectName("BeforeAfterLayout")
        self.Before = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Before.sizePolicy().hasHeightForWidth())
        self.Before.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.Before.setPalette(palette)
        self.Before.setMouseTracking(True)
        self.Before.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.Before.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/left-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.Before.setIcon(icon3)
        self.Before.setIconSize(QtCore.QSize(40, 40))
        self.Before.setCheckable(False)
        self.Before.setAutoExclusive(False)
        self.Before.setAutoDefault(False)
        self.Before.setDefault(False)
        self.Before.setFlat(True)
        self.Before.setObjectName("Before")
        self.BeforeAfterLayout.addWidget(self.Before)
        self.Right = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Right.sizePolicy().hasHeightForWidth())
        self.Right.setSizePolicy(sizePolicy)
        self.Right.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Right.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/right-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.Right.setIcon(icon4)
        self.Right.setIconSize(QtCore.QSize(40, 40))
        self.Right.setFlat(True)
        self.Right.setObjectName("Right")
        self.BeforeAfterLayout.addWidget(self.Right)
        self.ViewerImage_Layout.addLayout(self.BeforeAfterLayout)
        self.gridLayout_3.addLayout(self.ViewerImage_Layout, 0, 1, 1, 1)
        self.ListImage_Layout = QtWidgets.QVBoxLayout()
        self.ListImage_Layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ListImage_Layout.setObjectName("ListImage_Layout")
        self.AddImages = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.AddImages.setFont(font)
        self.AddImages.setObjectName("AddImages")
        self.ListImage_Layout.addWidget(self.AddImages)
        self.scrollAreaImages = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaImages.sizePolicy().hasHeightForWidth())
        self.scrollAreaImages.setSizePolicy(sizePolicy)
        self.scrollAreaImages.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollAreaImages.setWidgetResizable(True)
        self.scrollAreaImages.setObjectName("scrollAreaImages")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 150, 838))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollAreaImages.setWidget(self.scrollAreaWidgetContents)
        self.ListImage_Layout.addWidget(self.scrollAreaImages)
        self.DeleteAllImages = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.DeleteAllImages.setFont(font)
        self.DeleteAllImages.setObjectName("DeleteAllImages")
        self.ListImage_Layout.addWidget(self.DeleteAllImages)
        self.gridLayout_3.addLayout(self.ListImage_Layout, 0, 0, 1, 1)
        self.DataExif_Layout = QtWidgets.QVBoxLayout()
        self.DataExif_Layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.DataExif_Layout.setObjectName("DataExif_Layout")
        self.ExifData = QtWidgets.QTableWidget(self.centralwidget)
        self.ExifData.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExifData.sizePolicy().hasHeightForWidth())
        self.ExifData.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExifData.setFont(font)
        self.ExifData.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ExifData.setAutoFillBackground(False)
        self.ExifData.setFrameShape(QtWidgets.QFrame.HLine)
        self.ExifData.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ExifData.setLineWidth(6)
        self.ExifData.setMidLineWidth(0)
        self.ExifData.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ExifData.setTabKeyNavigation(False)
        self.ExifData.setProperty("showDropIndicator", False)
        self.ExifData.setAlternatingRowColors(False)
        self.ExifData.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ExifData.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ExifData.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.ExifData.setShowGrid(True)
        self.ExifData.setGridStyle(QtCore.Qt.SolidLine)
        self.ExifData.setCornerButtonEnabled(True)
        self.ExifData.setRowCount(30)
        self.ExifData.setColumnCount(2)
        self.ExifData.setObjectName("ExifData")
        item = QtWidgets.QTableWidgetItem()
        self.ExifData.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ExifData.setItem(0, 1, item)
        self.ExifData.horizontalHeader().setVisible(False)
        self.ExifData.horizontalHeader().setHighlightSections(False)
        self.ExifData.horizontalHeader().setMinimumSectionSize(200)
        self.ExifData.verticalHeader().setVisible(False)
        self.ExifData.verticalHeader().setCascadingSectionResizes(False)
        self.DataExif_Layout.addWidget(self.ExifData)
        self.gridLayout_3.addLayout(self.DataExif_Layout, 0, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_3)
        ExifViewer.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ExifViewer)
        self.statusbar.setObjectName("statusbar")
        ExifViewer.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(ExifViewer)
        self.toolBar.setObjectName("toolBar")
        ExifViewer.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.toolBar.addSeparator()

        self.retranslateUi(ExifViewer)
        QtCore.QMetaObject.connectSlotsByName(ExifViewer)

    def retranslateUi(self, ExifViewer):
        _translate = QtCore.QCoreApplication.translate
        ExifViewer.setWindowTitle(_translate("ExifViewer", "Exif data"))
        self.Geolocalization.setText(_translate("ExifViewer", "Geolocalization"))
        self.RotateLeft_2.setWhatsThis(_translate("ExifViewer", "Rotate Left"))
        self.RotateRight_2.setWhatsThis(_translate("ExifViewer", "Rotate Rigth"))
        self.AddImages.setText(_translate("ExifViewer", "Add Images"))
        self.DeleteAllImages.setText(_translate("ExifViewer", "Delete All"))
        __sortingEnabled = self.ExifData.isSortingEnabled()
        self.ExifData.setSortingEnabled(False)
        item = self.ExifData.item(0, 0)
        item.setText(_translate("ExifViewer", "Exif"))
        item = self.ExifData.item(0, 1)
        item.setText(_translate("ExifViewer", "Data"))
        self.ExifData.setSortingEnabled(__sortingEnabled)
        self.toolBar.setWindowTitle(_translate("ExifViewer", "toolBar"))

