# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exifViewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ExifViewer(object):
    def setupUi(self, ExifViewer):
        ExifViewer.setObjectName("ExifViewer")
        ExifViewer.resize(1920, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ExifViewer.sizePolicy().hasHeightForWidth())
        ExifViewer.setSizePolicy(sizePolicy)
        ExifViewer.setMinimumSize(QtCore.QSize(0, 0))
        ExifViewer.setMaximumSize(QtCore.QSize(1920, 1080))
        ExifViewer.setStyleSheet("")
        ExifViewer.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(ExifViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(1920, 1080))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.DataExifTab_Layout = QtWidgets.QHBoxLayout()
        self.DataExifTab_Layout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.DataExifTab_Layout.setObjectName("DataExifTab_Layout")
        self.ExifDataTab = QtWidgets.QTableWidget(self.centralwidget)
        self.ExifDataTab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExifDataTab.sizePolicy().hasHeightForWidth())
        self.ExifDataTab.setSizePolicy(sizePolicy)
        self.ExifDataTab.setMinimumSize(QtCore.QSize(400, 0))
        self.ExifDataTab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.ExifDataTab.setFont(font)
        self.ExifDataTab.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ExifDataTab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.ExifDataTab.setAutoFillBackground(False)
        self.ExifDataTab.setFrameShape(QtWidgets.QFrame.HLine)
        self.ExifDataTab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ExifDataTab.setLineWidth(6)
        self.ExifDataTab.setMidLineWidth(0)
        self.ExifDataTab.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.ExifDataTab.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.ExifDataTab.setAutoScroll(True)
        self.ExifDataTab.setAutoScrollMargin(5)
        self.ExifDataTab.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ExifDataTab.setTabKeyNavigation(False)
        self.ExifDataTab.setProperty("showDropIndicator", False)
        self.ExifDataTab.setDragDropOverwriteMode(False)
        self.ExifDataTab.setAlternatingRowColors(False)
        self.ExifDataTab.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.ExifDataTab.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ExifDataTab.setTextElideMode(QtCore.Qt.ElideRight)
        self.ExifDataTab.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.ExifDataTab.setShowGrid(True)
        self.ExifDataTab.setGridStyle(QtCore.Qt.SolidLine)
        self.ExifDataTab.setWordWrap(True)
        self.ExifDataTab.setCornerButtonEnabled(False)
        self.ExifDataTab.setRowCount(0)
        self.ExifDataTab.setColumnCount(2)
        self.ExifDataTab.setObjectName("ExifDataTab")
        self.ExifDataTab.horizontalHeader().setVisible(False)
        self.ExifDataTab.horizontalHeader().setDefaultSectionSize(650)
        self.ExifDataTab.horizontalHeader().setHighlightSections(False)
        self.ExifDataTab.horizontalHeader().setMinimumSectionSize(200)
        self.ExifDataTab.verticalHeader().setVisible(False)
        self.ExifDataTab.verticalHeader().setCascadingSectionResizes(False)
        self.ExifDataTab.verticalHeader().setDefaultSectionSize(30)
        self.ExifDataTab.verticalHeader().setMinimumSectionSize(15)
        self.DataExifTab_Layout.addWidget(self.ExifDataTab)
        self.gridLayout.addLayout(self.DataExifTab_Layout, 0, 1, 1, 1)
        self.externalGrid_layout = QtWidgets.QGridLayout()
        self.externalGrid_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.externalGrid_layout.setVerticalSpacing(0)
        self.externalGrid_layout.setObjectName("externalGrid_layout")
        self.ListImage_Layout = QtWidgets.QVBoxLayout()
        self.ListImage_Layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ListImage_Layout.setObjectName("ListImage_Layout")
        self.button_addImages = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_addImages.sizePolicy().hasHeightForWidth())
        self.button_addImages.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_addImages.setFont(font)
        self.button_addImages.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.button_addImages.setObjectName("button_addImages")
        self.ListImage_Layout.addWidget(self.button_addImages)
        spacerItem = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.ListImage_Layout.addItem(spacerItem)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = ListPreviewImages(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setAcceptDrops(True)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget.setEditTriggers(
            QtWidgets.QAbstractItemView.DoubleClicked | QtWidgets.QAbstractItemView.EditKeyPressed | QtWidgets.QAbstractItemView.SelectedClicked)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setIconSize(QtCore.QSize(150, 150))
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setUniformItemSizes(False)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem1)
        self.ListImage_Layout.addLayout(self.verticalLayout_2)
        self.button_deleteSelectedImages = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_deleteSelectedImages.sizePolicy().hasHeightForWidth())
        self.button_deleteSelectedImages.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_deleteSelectedImages.setFont(font)
        self.button_deleteSelectedImages.setObjectName("button_deleteSelectedImages")
        self.ListImage_Layout.addWidget(self.button_deleteSelectedImages)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.ListImage_Layout.addItem(spacerItem2)
        self.button_deleteAllImages = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_deleteAllImages.sizePolicy().hasHeightForWidth())
        self.button_deleteAllImages.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.button_deleteAllImages.setFont(font)
        self.button_deleteAllImages.setObjectName("button_deleteAllImages")
        self.ListImage_Layout.addWidget(self.button_deleteAllImages)
        self.externalGrid_layout.addLayout(self.ListImage_Layout, 0, 0, 1, 1)
        self.ViewerImage_Layout = QtWidgets.QVBoxLayout()
        self.ViewerImage_Layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ViewerImage_Layout.setSpacing(7)
        self.ViewerImage_Layout.setObjectName("ViewerImage_Layout")
        self.widgetImg = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widgetImg.sizePolicy().hasHeightForWidth())
        self.widgetImg.setSizePolicy(sizePolicy)
        self.widgetImg.setMinimumSize(QtCore.QSize(0, 0))
        self.widgetImg.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.widgetImg.setFont(font)
        self.widgetImg.setStyleSheet("")
        self.widgetImg.setObjectName("widgetImg")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widgetImg)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.image = ImageView(self.widgetImg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.image.sizePolicy().hasHeightForWidth())
        self.image.setSizePolicy(sizePolicy)
        self.image.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.image.setFont(font)
        self.image.setAcceptDrops(True)
        self.image.setAutoFillBackground(False)
        self.image.setStyleSheet("")
        self.image.setText("No image loaded")
        self.image.setScaledContents(False)
        self.image.setAlignment(QtCore.Qt.AlignCenter)
        self.image.setWordWrap(True)
        self.image.setObjectName("image")
        self.gridLayout_2.addWidget(self.image, 0, 0, 1, 1)
        self.ViewerImage_Layout.addWidget(self.widgetImg)
        self.BeforeAfterLayout = QtWidgets.QHBoxLayout()
        self.BeforeAfterLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.BeforeAfterLayout.setObjectName("BeforeAfterLayout")
        spacerItem3 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.BeforeAfterLayout.addItem(spacerItem3)
        self.button_previous = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_previous.sizePolicy().hasHeightForWidth())
        self.button_previous.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.button_previous.setPalette(palette)
        self.button_previous.setMouseTracking(True)
        self.button_previous.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.button_previous.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/left-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.button_previous.setIcon(icon)
        self.button_previous.setIconSize(QtCore.QSize(40, 40))
        self.button_previous.setCheckable(False)
        self.button_previous.setAutoExclusive(False)
        self.button_previous.setAutoDefault(False)
        self.button_previous.setDefault(False)
        self.button_previous.setFlat(True)
        self.button_previous.setObjectName("button_previous")
        self.BeforeAfterLayout.addWidget(self.button_previous, 0, QtCore.Qt.AlignHCenter)
        self.button_rotateLeft = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_rotateLeft.sizePolicy().hasHeightForWidth())
        self.button_rotateLeft.setSizePolicy(sizePolicy)
        self.button_rotateLeft.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/LeftRotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_rotateLeft.setIcon(icon1)
        self.button_rotateLeft.setIconSize(QtCore.QSize(40, 40))
        self.button_rotateLeft.setFlat(True)
        self.button_rotateLeft.setObjectName("button_rotateLeft")
        self.BeforeAfterLayout.addWidget(self.button_rotateLeft, 0, QtCore.Qt.AlignHCenter)
        self.button_rotateRight = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_rotateRight.sizePolicy().hasHeightForWidth())
        self.button_rotateRight.setSizePolicy(sizePolicy)
        self.button_rotateRight.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/RightRotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_rotateRight.setIcon(icon2)
        self.button_rotateRight.setIconSize(QtCore.QSize(40, 40))
        self.button_rotateRight.setFlat(True)
        self.button_rotateRight.setObjectName("button_rotateRight")
        self.BeforeAfterLayout.addWidget(self.button_rotateRight, 0, QtCore.Qt.AlignHCenter)
        self.button_next = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_next.sizePolicy().hasHeightForWidth())
        self.button_next.setSizePolicy(sizePolicy)
        self.button_next.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_next.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/right-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.button_next.setIcon(icon3)
        self.button_next.setIconSize(QtCore.QSize(40, 40))
        self.button_next.setFlat(True)
        self.button_next.setObjectName("button_next")
        self.BeforeAfterLayout.addWidget(self.button_next, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.BeforeAfterLayout.addItem(spacerItem4)
        self.ViewerImage_Layout.addLayout(self.BeforeAfterLayout)
        self.externalGrid_layout.addLayout(self.ViewerImage_Layout, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.externalGrid_layout, 0, 0, 1, 1)
        ExifViewer.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExifViewer)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(ExifViewer)

    def retranslateUi(self, ExifViewer):
        _translate = QtCore.QCoreApplication.translate
        ExifViewer.setWindowTitle(_translate("ExifViewer", "Exif data"))
        self.button_addImages.setText(_translate("ExifViewer", "Add Images"))
        self.listWidget.setSortingEnabled(False)
        self.button_deleteSelectedImages.setText(_translate("ExifViewer", "Delete Selected"))
        self.button_deleteAllImages.setText(_translate("ExifViewer", "Delete All"))
        self.button_rotateLeft.setWhatsThis(_translate("ExifViewer", "Rotate Left"))
        self.button_rotateRight.setWhatsThis(_translate("ExifViewer", "Rotate Rigth"))

from imageView import ImageView
from listPreviewImages import ListPreviewImages
