# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'exifViewer.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ExifViewer(object):
    def setupUi(self, ExifViewer):
        ExifViewer.setObjectName("ExifViewer")
        ExifViewer.resize(1864, 1007)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ExifViewer.sizePolicy().hasHeightForWidth())
        ExifViewer.setSizePolicy(sizePolicy)
        ExifViewer.setMinimumSize(QtCore.QSize(0, 0))
        ExifViewer.setMaximumSize(QtCore.QSize(1920, 1080))
        ExifViewer.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(ExifViewer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.externalGrid_layout = QtWidgets.QGridLayout()
        self.externalGrid_layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.externalGrid_layout.setVerticalSpacing(0)
        self.externalGrid_layout.setObjectName("externalGrid_layout")
        self.ViewerImage_Layout = QtWidgets.QVBoxLayout()
        self.ViewerImage_Layout.setObjectName("ViewerImage_Layout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.Geolocalization = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Geolocalization.sizePolicy().hasHeightForWidth())
        self.Geolocalization.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Geolocalization.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/pin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Geolocalization.setIcon(icon)
        self.Geolocalization.setIconSize(QtCore.QSize(40, 40))
        self.Geolocalization.setFlat(False)
        self.Geolocalization.setObjectName("Geolocalization")
        self.verticalLayout.addWidget(self.Geolocalization, 0, QtCore.Qt.AlignHCenter)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(1000, 20, QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.button_rotateLeft = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_rotateLeft.sizePolicy().hasHeightForWidth())
        self.button_rotateLeft.setSizePolicy(sizePolicy)
        self.button_rotateLeft.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/LeftRotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_rotateLeft.setIcon(icon1)
        self.button_rotateLeft.setIconSize(QtCore.QSize(40, 40))
        self.button_rotateLeft.setFlat(True)
        self.button_rotateLeft.setObjectName("button_rotateLeft")
        self.horizontalLayout.addWidget(self.button_rotateLeft, 0, QtCore.Qt.AlignRight | QtCore.Qt.AlignVCenter)
        self.button_rotateRight = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_rotateRight.sizePolicy().hasHeightForWidth())
        self.button_rotateRight.setSizePolicy(sizePolicy)
        self.button_rotateRight.setMinimumSize(QtCore.QSize(33, 27))
        self.button_rotateRight.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/RightRotate.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_rotateRight.setIcon(icon2)
        self.button_rotateRight.setIconSize(QtCore.QSize(40, 40))
        self.button_rotateRight.setFlat(True)
        self.button_rotateRight.setObjectName("button_rotateRight")
        self.horizontalLayout.addWidget(self.button_rotateRight, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.ViewerImage_Layout.addLayout(self.verticalLayout)
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding,
                                           QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(2000, 2000))
        self.label.setAcceptDrops(True)
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../Pictures/Screenshot from 2020-07-19 22-26-23.png"))
        self.label.setScaledContents(True)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.ViewerImage_Layout.addWidget(self.label, 0, QtCore.Qt.AlignHCenter | QtCore.Qt.AlignVCenter)
        self.BeforeAfterLayout = QtWidgets.QHBoxLayout()
        self.BeforeAfterLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.BeforeAfterLayout.setObjectName("BeforeAfterLayout")
        self.button_next = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_next.sizePolicy().hasHeightForWidth())
        self.button_next.setSizePolicy(sizePolicy)
        self.button_next.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_next.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/right-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.button_next.setIcon(icon3)
        self.button_next.setIconSize(QtCore.QSize(40, 40))
        self.button_next.setFlat(True)
        self.button_next.setObjectName("button_next")
        self.BeforeAfterLayout.addWidget(self.button_next)
        self.button_previous = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.button_previous.sizePolicy().hasHeightForWidth())
        self.button_previous.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(238, 238, 236))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        self.button_previous.setPalette(palette)
        self.button_previous.setMouseTracking(True)
        self.button_previous.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.button_previous.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("icons/left-arrow.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        self.button_previous.setIcon(icon4)
        self.button_previous.setIconSize(QtCore.QSize(40, 40))
        self.button_previous.setCheckable(False)
        self.button_previous.setAutoExclusive(False)
        self.button_previous.setAutoDefault(False)
        self.button_previous.setDefault(False)
        self.button_previous.setFlat(True)
        self.button_previous.setObjectName("button_previous")
        self.BeforeAfterLayout.addWidget(self.button_previous)
        self.ViewerImage_Layout.addLayout(self.BeforeAfterLayout)
        self.externalGrid_layout.addLayout(self.ViewerImage_Layout, 0, 1, 1, 1)
        self.ListImage_Layout = QtWidgets.QVBoxLayout()
        self.ListImage_Layout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.ListImage_Layout.setObjectName("ListImage_Layout")
        self.button_addImages = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_addImages.setFont(font)
        self.button_addImages.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.button_addImages.setObjectName("button_addImages")
        self.ListImage_Layout.addWidget(self.button_addImages)
        spacerItem1 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.ListImage_Layout.addItem(spacerItem1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setAcceptDrops(True)
        self.listWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.listWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.listWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.listWidget.setDragEnabled(True)
        self.listWidget.setDragDropMode(QtWidgets.QAbstractItemView.DragDrop)
        self.listWidget.setDefaultDropAction(QtCore.Qt.IgnoreAction)
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.MultiSelection)
        self.listWidget.setIconSize(QtCore.QSize(100, 100))
        self.listWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.listWidget.setProperty("isWrapping", False)
        self.listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setModelColumn(0)
        self.listWidget.setUniformItemSizes(False)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_2.addWidget(self.listWidget)
        spacerItem2 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem2)
        self.ListImage_Layout.addLayout(self.verticalLayout_2)
        self.button_deleteSelectedImages = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_deleteSelectedImages.setFont(font)
        self.button_deleteSelectedImages.setObjectName("button_deleteSelectedImages")
        self.ListImage_Layout.addWidget(self.button_deleteSelectedImages)
        spacerItem3 = QtWidgets.QSpacerItem(10, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.ListImage_Layout.addItem(spacerItem3)
        self.button_deleteAllImages = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.button_deleteAllImages.setFont(font)
        self.button_deleteAllImages.setObjectName("button_deleteAllImages")
        self.ListImage_Layout.addWidget(self.button_deleteAllImages)
        self.externalGrid_layout.addLayout(self.ListImage_Layout, 0, 0, 1, 1)
        self.DataExifTab_Layout = QtWidgets.QVBoxLayout()
        self.DataExifTab_Layout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.DataExifTab_Layout.setObjectName("DataExifTab_Layout")
        self.ExifDataTab = QtWidgets.QTableWidget(self.centralwidget)
        self.ExifDataTab.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ExifDataTab.sizePolicy().hasHeightForWidth())
        self.ExifDataTab.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.ExifDataTab.setFont(font)
        self.ExifDataTab.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.ExifDataTab.setAutoFillBackground(False)
        self.ExifDataTab.setFrameShape(QtWidgets.QFrame.HLine)
        self.ExifDataTab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.ExifDataTab.setLineWidth(6)
        self.ExifDataTab.setMidLineWidth(0)
        self.ExifDataTab.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.ExifDataTab.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.ExifDataTab.setAutoScroll(True)
        self.ExifDataTab.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.ExifDataTab.setTabKeyNavigation(False)
        self.ExifDataTab.setProperty("showDropIndicator", False)
        self.ExifDataTab.setAlternatingRowColors(False)
        self.ExifDataTab.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.ExifDataTab.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.ExifDataTab.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.ExifDataTab.setShowGrid(True)
        self.ExifDataTab.setGridStyle(QtCore.Qt.SolidLine)
        self.ExifDataTab.setCornerButtonEnabled(True)
        self.ExifDataTab.setRowCount(30)
        self.ExifDataTab.setColumnCount(2)
        self.ExifDataTab.setObjectName("ExifDataTab")
        item = QtWidgets.QTableWidgetItem()
        self.ExifDataTab.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ExifDataTab.setItem(0, 1, item)
        self.ExifDataTab.horizontalHeader().setVisible(False)
        self.ExifDataTab.horizontalHeader().setHighlightSections(False)
        self.ExifDataTab.horizontalHeader().setMinimumSectionSize(200)
        self.ExifDataTab.verticalHeader().setVisible(False)
        self.ExifDataTab.verticalHeader().setCascadingSectionResizes(False)
        self.DataExifTab_Layout.addWidget(self.ExifDataTab)
        self.externalGrid_layout.addLayout(self.DataExifTab_Layout, 0, 2, 1, 1)
        self.gridLayout.addLayout(self.externalGrid_layout, 0, 0, 1, 1)
        ExifViewer.setCentralWidget(self.centralwidget)

        self.retranslateUi(ExifViewer)
        self.listWidget.setCurrentRow(-1)
        QtCore.QMetaObject.connectSlotsByName(ExifViewer)

    def retranslateUi(self, ExifViewer):
        _translate = QtCore.QCoreApplication.translate
        ExifViewer.setWindowTitle(_translate("ExifViewer", "Exif data"))
        self.Geolocalization.setText(_translate("ExifViewer", "Geolocalization"))
        self.button_rotateLeft.setWhatsThis(_translate("ExifViewer", "Rotate Left"))
        self.button_rotateRight.setWhatsThis(_translate("ExifViewer", "Rotate Rigth"))
        self.button_addImages.setText(_translate("ExifViewer", "Add Images"))
        self.listWidget.setSortingEnabled(False)
        self.button_deleteSelectedImages.setText(_translate("ExifViewer", "Delete Selected"))
        self.button_deleteAllImages.setText(_translate("ExifViewer", "Delete All"))
        __sortingEnabled = self.ExifDataTab.isSortingEnabled()
        self.ExifDataTab.setSortingEnabled(False)
        item = self.ExifDataTab.item(0, 0)
        item.setText(_translate("ExifViewer", "Exif"))
        item = self.ExifDataTab.item(0, 1)
        item.setText(_translate("ExifViewer", "Data"))
        self.ExifDataTab.setSortingEnabled(__sortingEnabled)
